version: '3.3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    command: postgres -c 'max_connections=50'
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - ./data/dumps:/dumps
    environment:
      - POSTGRES_DB=blcmdb
      - POSTGRES_USER=ars
      - POSTGRES_PASSWORD=ars
      
  backend:
    build:
      context: ./backend/
      args:
        PROFILE: dev
    image: backend
    container_name: backend
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING.DATASOURCE.USERNAME=ars
      - SPRING.DATASOURCE.PASSWORD=ars
      - SPRING.JPA.DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/blcmdb

  tournament-tests:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD/backend/
    volumes:
      - $PWD:$PWD
#      - ~/.m2:/root/.m2
    command: mvn -Ptest test -Dtest=TournamentFunctionalityTest
