version: '3.3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    command: postgres -c 'max_connections=50'
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data/dumps:/dumps
    environment:
      - POSTGRES_DB=blcmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  backend:
    build:
      context: ./backend/
      args:
        PROFILE: dev
    image: backend
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING.DATASOURCE.USERNAME=postgres
      - SPRING.DATASOURCE.PASSWORD=postgres
      - SPRING.JPA.DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/blcmdb

  unit-tests:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD/backend/
    volumes:
      - $PWD:$PWD
#      - ~/.m2:/root/.m2
    command: mvn -Ptest test

  test-fig3a:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD/backend/
    volumes:
      - $PWD:$PWD
#      - ~/.m2:/root/.m2
    command: mvn -Ptest test -Dtest=TournamentFunctionalityTest#'sequential update name in course execution and then add student as tournament participant'

  test-fig3b:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD/backend/
    volumes:
      - $PWD:$PWD
#      - ~/.m2:/root/.m2
    command: mvn -Ptest test -Dtest=TournamentFunctionalityTest#'sequential add student as tournament participant and then update name in course execution'

  test-fig3c:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD/backend/
    volumes:
      - $PWD:$PWD
#      - ~/.m2:/root/.m2
    command: mvn -Ptest test -Dtest=TournamentFunctionalityTest#'concurrent add student as tournament participant and update name in course execution - add student finishes first'

  test-fig3d:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD/backend/
    volumes:
      - $PWD:$PWD
#      - ~/.m2:/root/.m2
    command: mvn -Ptest test -Dtest=TournamentFunctionalityTest#'concurrent add student as tournament participant and update name in course execution - update name finishes first'

  test-fig4:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD/backend/
    volumes:
      - $PWD:$PWD
#      - ~/.m2:/root/.m2
    command: mvn -Ptest test -Dtest=TournamentFunctionalityTest#'concurrent add creator as tournament participant and update name in course execution - update name finishes first and event processing starts before add creator finishes'
